name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo service postgresql start
          # Create user and database for your tests
          sudo -u postgres psql -c "CREATE USER github WITH PASSWORD 'password';"
          sudo -u postgres psql -c "CREATE DATABASE employeedb OWNER github;"

      - name: Build and Run Tests
        run: mvn clean test -B
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/employeedb
          SPRING_DATASOURCE_USERNAME: github
          SPRING_DATASOURCE_PASSWORD: password

      - name: Show Maven test results
        run: cat target/surefire-reports/*.txt || true

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
